{:config {:order 0, :description "Normal", :name :normal}
 :data
 [
  [:node-create [] :map]
  [:node-create [:login] :map]
  [:node-create [:login :name] :map]
  [:transform-enable [:login :name] :login [{:io.pedestal.app.messages/topic [:login :name], :io.pedestal.app.messages/type :swap, :io.pedestal.app.messages.param/value {}}]]
  :break
  [:value [:login :name] nil "James"]
  [:transform-disable [:login :name] :login [{:io.pedestal.app.messages/topic [:login :name], :io.pedestal.app.messages/type :swap, :io.pedestal.app.messages.param/value {}}]]
  [:node-create [:login :my-answer] :map]
  [:transform-enable [:login :my-answer] :add-answer [{:io.pedestal.app.messages/topic [:answers :mine], :io.pedestal.app.messages.param/answer {}}]]
  :break
  [:value [:login :my-answer] nil 21]
  :break
  [:value [:login :name] "James" nil]
  [:node-destroy [:login :name] :map]
  [:value [:login :my-answer] 21 nil]
  [:transform-disable [:login :my-answer] :add-answer [{:io.pedestal.app.messages/topic [:answers :mine], :io.pedestal.app.messages.param/answer {}}]]
  [:node-destroy [:login :my-answer] :map]
  [:node-destroy [:login] :map]
  [:node-create [:wait] :map]
  [:node-create [:wait :start] :map]
  [:transform-enable [:wait :start] :start-game [{:io.pedestal.app.messages/topic :io.pedestal.app.messages/output, :payload {:io.pedestal.app.messages/type :swap, :io.pedestal.app.messages/topic [:active-game], :value true}} {:io.pedestal.app.messages/type :swap, :io.pedestal.app.messages/topic [:active-game], :value true}]]
  [:node-create [:wait :answers] :map]
  [:node-create [:wait :answers :mine] :map]
  [:value [:wait :answers :mine] nil 21]
  [:node-create [:wait :answers "player-xyz"] :map]
  [:value [:wait :answers "player-xyz"] nil 14]
  [:node-create [:wait :answers "player-abc"] :map]
  [:value [:wait :answers "player-abc"] nil 17]
  [:node-create [:wait :player] :map]
  [:node-create [:wait :player :name] :map]
  [:value [:wait :player :name] nil "James"]
  :break
  [:transform-disable [:wait :start] :start-game [{:io.pedestal.app.messages/topic :io.pedestal.app.messages/output, :payload {:io.pedestal.app.messages/type :swap, :io.pedestal.app.messages/topic [:active-game], :value true}} {:io.pedestal.app.messages/type :swap, :io.pedestal.app.messages/topic [:active-game], :value true}]]
  [:node-destroy [:wait :start] :map]
  [:value [:wait :answers :mine] 21 nil]
  [:node-destroy [:wait :answers :mine] :map]
  [:value [:wait :answers "player-xyz"] 14 nil]
  [:node-destroy [:wait :answers "player-xyz"] :map]
  [:value [:wait :answers "player-abc"] 17 nil]
  [:node-destroy [:wait :answers "player-abc"] :map]
  [:node-destroy [:wait :answers] :map]
  [:value [:wait :player :name] "James" nil]
  [:node-destroy [:wait :player :name] :map]
  [:node-destroy [:wait :player] :map]
  [:node-destroy [:wait] :map]
  [:node-create [:wits] :map]
  [:node-create [:wits :finish] :map]
  [:transform-enable [:wits :finish] :finish-game [{:io.pedestal.app.messages/type :io.pedestal.app.messages/output, :payload {:io.pedestal.app.messages/type :swap, :io.pedestal.app.messages/topic [:active-game], :value false}} {:io.pedestal.app.messages/type :swap, :io.pedestal.app.messages/topic [:active-game], :value false}]]
  [:node-create [:board] :vector]
  [:node-create [:board 0] :map]
  [:node-create [:board 0 :bids] :map]
  [:node-create [:board 1] :map]
  [:node-create [:board 1 :bids] :map]
  [:node-create [:board 2] :map]
  [:node-create [:board 2 :bids] :map]
  [:node-create [:board 3] :map]
  [:node-create [:board 3 :bids] :map]
  [:node-create [:board 4] :map]
  [:node-create [:board 4 :bids] :map]
  [:node-create [:board 5] :map]
  [:node-create [:board 5 :bids] :map]
  [:node-create [:board 6] :map]
  [:node-create [:board 6 :bids] :map]
  [:node-create [:board 7] :map]
  [:node-create [:board 7 :bids] :map]
  [:node-create [:board 0 :odds] :map]
  [:value [:board 0 :odds] nil 6]
  [:transform-enable [:board 5] :add-bid [{:io.pedestal.app.messages/topic [:bids :mine 5], :io.pedestal.app.messages.param/bid {}}]]
  [:transform-enable [:board 3] :add-bid [{:io.pedestal.app.messages/topic [:bids :mine 3], :io.pedestal.app.messages.param/bid {}}]]
  [:transform-enable [:board 4] :add-bid [{:io.pedestal.app.messages/topic [:bids :mine 4], :io.pedestal.app.messages.param/bid {}}]]
  [:node-create [:board 0 :answerers] :map]
  [:node-create [:board 7 :value] :map]
  [:node-create [:board 6 :value] :map]
  [:node-create [:board 5 :value] :map]
  [:value [:board 5 :value] nil 21]
  [:node-create [:board 3 :value] :map]
  [:value [:board 3 :value] nil 14]
  [:node-create [:board 4 :value] :map]
  [:value [:board 4 :value] nil 17]
  [:node-create [:board 0 :value] :map]
  [:node-create [:board 1 :value] :map]
  [:node-create [:board 2 :value] :map]
  [:node-create [:board 2 :odds] :map]
  [:value [:board 2 :odds] nil 4]
  [:node-create [:board 7 :answerers] :map]
  [:node-create [:board 1 :odds] :map]
  [:value [:board 1 :odds] nil 5]
  [:node-create [:board 4 :odds] :map]
  [:value [:board 4 :odds] nil 2]
  [:node-create [:board 5 :answerers] :map]
  [:value [:board 5 :answerers] nil [:mine]]
  [:node-create [:board 3 :odds] :map]
  [:value [:board 3 :odds] nil 3]
  [:node-create [:board 6 :answerers] :map]
  [:node-create [:board 2 :answerers] :map]
  [:node-create [:board 7 :odds] :map]
  [:value [:board 7 :odds] nil 5]
  [:node-create [:board 1 :answerers] :map]
  [:node-create [:board 4 :answerers] :map]
  [:value [:board 4 :answerers] nil ["player-abc"]]
  [:node-create [:board 5 :odds] :map]
  [:value [:board 5 :odds] nil 3]
  [:node-create [:board 3 :answerers] :map]
  [:value [:board 3 :answerers] nil ["player-xyz"]]
  [:node-create [:board 6 :odds] :map]
  [:value [:board 6 :odds] nil 4]
  [:node-create [:wits :player] :map]
  [:node-create [:wits :player :name] :map]
  [:value [:wits :player :name] nil "James"]
  :break
  [:node-create [:board 1 :bids "player-abc"] :map]
  [:value [:board 1 :bids "player-abc"] nil 1]
  :break
  [:node-create [:board 6 :bids "player-xyz"] :map]
  [:value [:board 6 :bids "player-xyz"] nil 1]
  :break
  [:node-create [:board 4 :bids "player-abc"] :map]
  [:value [:board 4 :bids "player-abc"] nil 3]
  :break
  [:node-create [:board 4 :bids :mine] :map]
  [:value [:board 4 :bids :mine] nil 2]
  [:transform-enable [:board 4] :remove-bid [{:io.pedestal.app.messages/topic [:bids :mine 4]}]]
  [:transform-disable [:board 4] :add-bid [{:io.pedestal.app.messages/topic [:bids :mine 4], :io.pedestal.app.messages.param/bid {}}] [{:io.pedestal.app.messages/topic [:bids :mine 4], :io.pedestal.app.messages.param/bid {}}]]
  :break
  [:value [:board 6 :bids "player-xyz"] 1 3]
  :break
  [:node-create [:board 5 :bids :mine] :map]
  [:value [:board 5 :bids :mine] nil 1]
  [:transform-enable [:board 5] :remove-bid [{:io.pedestal.app.messages/topic [:bids :mine 5]}]]
  [:transform-disable [:board 5] :add-bid [{:io.pedestal.app.messages/topic [:bids :mine 5], :io.pedestal.app.messages.param/bid {}}] [{:io.pedestal.app.messages/topic [:bids :mine 5], :io.pedestal.app.messages.param/bid {}}]]
  [:transform-disable [:board 3] :add-bid [{:io.pedestal.app.messages/topic [:bids :mine 3], :io.pedestal.app.messages.param/bid {}}] [{:io.pedestal.app.messages/topic [:bids :mine 3], :io.pedestal.app.messages.param/bid {}}]]
  :break
  [:transform-enable [:board 3] :add-bid [{:io.pedestal.app.messages/topic [:bids :mine 3], :io.pedestal.app.messages.param/bid {}}]]
  [:transform-disable [:board 4] :remove-bid [{:io.pedestal.app.messages/topic [:bids :mine 4]}] [{:io.pedestal.app.messages/topic [:bids :mine 4]}]]
  [:transform-enable [:board 4] :add-bid [{:io.pedestal.app.messages/topic [:bids :mine 4], :io.pedestal.app.messages.param/bid {}}]]
  [:value [:board 4 :bids :mine] 2 nil]
  [:node-destroy [:board 4 :bids :mine] :map]
  :break
  [:node-create [:board 3 :bids :mine] :map]
  [:value [:board 3 :bids :mine] nil 2]
  [:transform-enable [:board 3] :remove-bid [{:io.pedestal.app.messages/topic [:bids :mine 3]}]]
  [:transform-disable [:board 3] :add-bid [{:io.pedestal.app.messages/topic [:bids :mine 3], :io.pedestal.app.messages.param/bid {}}] [{:io.pedestal.app.messages/topic [:bids :mine 3], :io.pedestal.app.messages.param/bid {}}]]
  [:transform-disable [:board 4] :add-bid [{:io.pedestal.app.messages/topic [:bids :mine 4], :io.pedestal.app.messages.param/bid {}}] [{:io.pedestal.app.messages/topic [:bids :mine 4], :io.pedestal.app.messages.param/bid {}}]]
 ]}
